### ISSUE TITLE
Duplicate Assets

### ISSUE THREAD

**Issue by DaveyNedap** [jsamr/react-native-font-demo#2]
Hello!

We are truly grateful for your solution, however we do have 1 problem.

Currently the fonts assets will be duplicated ( `assets/fonts` and `android/app/src/main/res/font`).

Is there a way to only include the fonts one in your react-native app?

**Comment by jsamr** [comment]
Well, you have to remove these manually, see https://github.com/jsamr/react-native-font-demo#link
I'm not aware of another solution ATM.
