### ISSUE TITLE
XML font resourse file can’t find font files

### ISSUE THREAD

**Issue by Alyxdev-xyz** [jsamr/react-native-font-demo#6]
**Description:**

Following strictly the instructions to install font variants on a react native project doesn’t work anymore.

**Expected:**

The app runs on android and shows text bodies with different font variations.

**Result:**

The app compiles but crashes at start.

`addCustomFont` fails to load the resource.

**Steps to reproduce:**

Follow the installation instructions to the end.

**Environment:**

React-Native **0.70**  
Macbook pro M1 2021 — _MacOS Monterey_

**Comment by rtauziac** [comment]
I was somehow mislead by the embed assets copied with `npx react-native-asset` and made wrong assumptions.

The app font files were copied by react native at `src/main/assets/fonts` and not `src/main/res/font`

---

After completing the instructions, I was with the following file structure:

    android
        ﹂ src
            ﹂ main
                ﹂ assets
                    ﹂ fonts
                        ﹂ <list of fonts with file name restrictions>
                ﹂ res
                    ﹂ font
                        ﹂ <fontFamilyName.xml>

You need to have the files copied and not moved in both

**Comment by Alyxdev-xyz** [comment]
I was somehow mislead by the embed assets copied with `npx react-native-asset` and made wrong assumptions.

The app font files were copied by react native at `src/main/assets/fonts` and not `src/main/res/font`

---

After completing the instructions, I was with the following file structure:

    android
        ﹂ src
            ﹂ main
                ﹂ assets
                    ﹂ fonts
                        ﹂ <list of fonts with file name restrictions>
                ﹂ res
                    ﹂ font
                        ﹂ <fontFamilyName.xml>

You need to have the files copied and not moved in both destinations.

    android
        ﹂ src
            ﹂ main
                ﹂ assets
                    ﹂ fonts
                        ﹂ <list of fonts>
                ﹂ res
                    ﹂ font
                        ﹂ <fontFamilyName.xml>
                        ﹂ <list of fonts with file name restrictions>

That way you can still reference font by file name inside your code.
